name: Publish artifacts
description: Publish artifacts

runs:
  using: composite
  steps:
    - name: 📥 Collect artifacts
      run: tools/artifacts/_stage_all.ps1
      shell: pwsh
      if: always()

    # TODO: replace this hard-coded list with a loop that utilizes the NPM package at
    # https://github.com/actions/toolkit/tree/main/packages/artifact (or similar) to push the artifacts.

    - name: 📢 Upload project.assets.json files
      if: always()
      uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f # v7.0.0
      with:
        name: projectAssetsJson-${{ runner.os }}
        path: ${{ runner.temp }}/_artifacts/projectAssetsJson
        retention-days: 1
      continue-on-error: true
    - name: 📢 Upload variables
      uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f # v7.0.0
      with:
        name: variables-${{ runner.os }}
        path: ${{ runner.temp }}/_artifacts/Variables
        retention-days: 1
      continue-on-error: true
    - name: 📢 Upload build_logs
      if: always() && (github.event_name != 'pull_request' || failure())
      uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f # v7.0.0
      with:
        name: build_logs-${{ runner.os }}
        path: ${{ runner.temp }}/_artifacts/build_logs
        retention-days: 1
      continue-on-error: true
    - name: 📢 Upload testResults
      if: always()
      uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f # v7.0.0
      with:
        name: testResults-${{ runner.os }}
        path: ${{ runner.temp }}/_artifacts/testResults
        retention-days: 1
      continue-on-error: true
    - name: 📢 Upload coverageResults
      if: always()
      uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f # v7.0.0
      with:
        name: coverageResults-${{ runner.os }}
        path: ${{ runner.temp }}/_artifacts/coverageResults
        retention-days: 1
      continue-on-error: true
    - name: 📢 Upload symbols
      uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f # v7.0.0
      with:
        name: symbols-${{ runner.os }}
        path: ${{ runner.temp }}/_artifacts/symbols
        retention-days: 1
      continue-on-error: true
    - name: 📢 Upload rust
      uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f # v7.0.0
      with:
        name: rust-${{ runner.os }}
        path: ${{ runner.temp }}/_artifacts/rust
        retention-days: 1
      if: always()
    - name: 📢 Upload ios_framework
      uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f # v7.0.0
      with:
        name: ios_framework
        path: ${{ runner.temp }}/_artifacts/ios_framework
        retention-days: 1
      if: startsWith(matrix.os, 'macos')
