[package]
name = "nerdbank-qrcodes"
version = "0.1.0"
license = "MIT"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[profile.release]
lto = true
opt-level = 'z'
codegen-units = 1

[dependencies]
encoding = "0.2.33"
image = "0.25.1"
rqrr = "0.7.1"
