parameters:
- name: signArtifacts
  type: boolean

steps:
- task: DownloadPipelineArtifact@2
  displayName: 🔻 Download Windows binaries
  inputs:
    buildType: current
    targetPath: src/nerdbank-qrcodes/target
    artifactName: rust-Windows
- task: DownloadPipelineArtifact@2
  displayName: 🔻 Download Linux binaries
  inputs:
    buildType: current
    targetPath: src/nerdbank-qrcodes/target
    artifactName: rust-Linux
- task: DownloadPipelineArtifact@2
  displayName: 🔻 Download android binaries
  inputs:
    buildType: current
    targetPath: src/nerdbank-qrcodes/target
    artifactName: rust-android
- task: DownloadPipelineArtifact@2
  displayName: 🔻 Download macOS binaries
  inputs:
    buildType: current
    targetPath: src/nerdbank-qrcodes/target
    artifactName: rust-macOS

- pwsh: src/nerdbank-qrcodes/Generate-3rdPartyNotices.ps1
  displayName: 🪪 3rd party licenses

- script: dotnet pack --no-restore -c $(BuildConfiguration) -warnaserror /bl:"$(Build.ArtifactStagingDirectory)/build_logs/pack_x64.binlog"
  displayName: 🛠 pack

- powershell: azure-pipelines/artifacts/_pipelines.ps1 -ArtifactNameSuffix "-$(Agent.JobName)" -Verbose
  failOnStderr: true
  displayName: 📢 Publish artifacts
  condition: succeededOrFailed()

- powershell: dotnet nuget push 'bin/Packages/$(BuildConfiguration)/NuGet/*.nupkg' -s $(ci_feed) -k azdo --skip-duplicate
  displayName: 📦 Push packages to CI feed
  condition: and(succeeded(), ne(variables['ci_feed'], ''), ne(variables['Build.Reason'], 'PullRequest'))
